### ISSUE TITLE
About the distance of the proportions label from the center

### ISSUE THREAD

**Issue by lbwfff** [PaoloDalena/tastypie#3]
Hi, PaoloDalena

Thanks for the excellent tool, I would like to know how to adjust the distance of the proportions label from the center of the pie chart in the pie chart drawn by tastepie? Because I found that sometimes the proportions labels would overlap.

Thanks,
LeeLee

**Comment by PaoloDalena** [comment]
Dear LeeLee, sorry for the huge delay but I was busy with so many other projects. I'm replying anyway because maybe it will come in handy for someone in the future - in the next version I will include this trick in vignettes as well or maybe as an option in the functions.

To decide the distance in which to place the percentages you have to specify perc = F in pie_bake change the aes x in shadowtext::geom_shadowtext().

Below is an example on how to do this, with a random dataset and the template "basic1":

```
library(tastypie)
library(ggplot2)
set.seed(123)

pie_bake(
  data = data.frame(LETTERS[1:15], rnorm(15, 1000, 500)),
  template = "basic1",
  perc = F
) +
  shadowtext::geom_shadowtext(
    aes(
      y = value / 2 + c(0, cumsum(value)[-length(value)]),
      label = (scales::label_percent(accuracy = 1))(value / sum(value)),
      x = 1.5
    ),
    color = "black",
    bg.color = "white",
    family = "mono",
    sfontface = "bold",
    size = 5
  )
```

Please note that not specifying perc = F in pie_bake() creates two percentages because geom_shadowtext is called once in pie_bake() and then a second time outside the function.

Also, in this example, the percentages are put at the outermost point of the pie, but you can arbitrarily choose the distance from the center by choosing different values of x between 0 and 1.5.

Thank you for the report,
Paolo
